version: '3.1'

services:
#  app:
#    image: paolocngei/assemblee:latest
#    ports:
#      - 8080:8080
#    environment:
#      SPRING_DATASOURCE_URL: 'jdbc:postgresql://db:5432/postgres'
  db:
    image: postgres:17
    restart: always
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
  redis:
    image: redis:latest
    restart: always
    ports:
      - 6379:6379
