spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: password
    url: jdbc:postgresql://localhost:5432/postgres
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    defer-datasource-initialization: true
keycloak:
  auth-server-url: https://auth.cngei.it/auth
  realm: cngei
  resource: assemblee
  public-client: true
  security-constraints:
    - auth-roles:
        - user
    - security-collections:
        - patterns:
            - /**